stages:
  - build
  - test

build-frontend:
  stage: build
  image: node
  script: 
    - echo "Start building Frontend App"
    - cd frontend
    - npm install
    - npm run-script build
    - echo "Build successfully!"
  artifacts:
    expire_in: 1 hour
    paths:
    - frontend/build
    - frontend/node_modules/

test-frontend:
  stage: test
  image: node
  script:
    - echo "Testing Frontend App"
    - cd frontend
    - CI=true npm test
    - echo "Test successfully!"
