stages:
  - build
  - test

build-frontend:
  stage: build
  image: node
  script: 
    - echo "Start building Frontend App"
    - cd frontend
    - npm install
    - npm run-script build
    - echo "Build successfully!"
    
compile-backend:
  stage: build
  image: node
  script: 
    - echo "Start building Backend App"
    - cd backend
    - npm install
    - echo "Build successfully!"

test-frontend:
  stage: test
  image: node
  script:
    - echo "Testing Frontend App"
    - cd frontend
    - npm install
    - CI=true npm test
    - echo "Test successfully!"
    
test-backend:
  stage: test
  image: node
  script:
    - echo "Testing Backend App"
    - cd backend
    - npm install
    - CI=true npm test
    - echo "Test successfully!"
